### ISSUE TITLE
[testcontainers-go] Named volumes don't get cleaned up by Ryuk

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/moby-ryuk#103]
> @mdelapenya in case you missed it, please have a look at my additional demo above ([#2163 (comment)](https://github.com/testcontainers/testcontainers-go/issues/2163#issuecomment-1919561727)), which shows how named volumes don't get cleaned up by Ryuk.

I think we should open a bug in https://github.com/testcontainers/moby-ryuk

_Originally posted by @mdelapenya in https://github.com/testcontainers/testcontainers-go/issues/2163#issuecomment-1922500478_

**Comment by mdelapenya** [comment]
Mmm wrong repo. I think the issue comes from testcontainers-go, closing

**Comment by srabraham** [comment]
Yeah, there was some relevant activity in moby-ryuk almost a year ago, see
https://github.com/docker/cli/issues/4028
https://github.com/docker/cli/issues/4028
https://github.com/testcontainers/moby-ryuk/issues/79

but maybe some additional work was needed in the testcontainers implementation repos too
