### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by rathboma** [testcontainers/moby-ryuk#15]
I run unit test suites on both x64 and arm64 and use testcontainers-node.

Unfortunately I have to disable the ryuk container on arm64, but I'd like to enable it!

Would it be possible to add an arm64 build of the container?

**Comment by adriancole** [comment]
Here's the Dockerfile I used to temporarily work around this and #16 I suspect it is cheating a little, but hope the tips help:

```Dockerfile
FROM golang:1.15.4-alpine3.12 as workspace
WORKDIR /go/src/github.com/testcontainers/moby-ryuk
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 go build -i -v -ldflags '-s' -o ./bin/moby-ryuk ./


FROM alpine:3.12.1
RUN apk --no-cache add ca-certificates
COPY --from=workspace /go/src/github.com/testcontainers/moby-ryuk/bin/moby-ryuk /app
CMD ["/app"]
```

```bash
docker buildx build --progress plain --tag ghcr.io/openzipkin/testcontainers-ryuk:latest --platform=linux/amd64,linux/arm64 --push .
```

buildx was setup with qemu per https://github.com/openzipkin/zipkin/blob/master/build-bin/setup_multiarch_docker

**Comment by adriancole** [comment]
once this is done, zipkin can switch to the main images (which also helps remove a log message about overriding them)

Note: we are also asked recently about s390x https://github.com/openzipkin/zipkin/issues/3310

**Comment by adriancole** [comment]
`tls: invalid signature by the server certificate: ECDSA verification failure` on s390x

mentioned here https://github.com/golang/go/issues/40949

**Comment by sscarduzio** [comment]
16:20:39.429 [scala-execution-context-global-12] ERROR org.testcontainers.utility.ResourceReaper - Timed out waiting for Ryuk container to start. Ryuk's logs:
standard_init_linux.go:211: exec user process caused "exec format error"

We are blocked too on this.

**Comment by rnorth** [comment]
This was done in #21
