### ISSUE TITLE
Publish to GitHub Docker Registry

### ISSUE THREAD

**Issue by adriancole** [testcontainers/moby-ryuk#16]
In zipkin, we'd like to reduce the risk of build outages for anyone running our build (ex ourselves, as well as people forking zipkin of which there are many). An easy way is to stop using docker hub registry during the build process. We've eliminated nearly all image pulls we can find, but I suspect ryuk is still implicitly pulling from docker hub. Can you publish this also to GitHub Container registry?

Note: So far, we've not found a mirror for alpine that supports arm64, so while publishing to github should be fine, you might have trouble with FROM. That said, consumers can still benefit even if this repo can't purely depend on GHCR.

**Comment by adriancole** [comment]
Hi, this is particularly important or otherwise, could we get this reversed?

```
14:24:46,598 WARN  [main] utility.ConfigurationFileImageNameSubstitutor (ConfigurationFileImageNameSubstitutor.java:31) - Image name testcontainers/ryuk:0.3.0 was substituted by configuration to ghcr.io/openzipkin/testcontainers-ryuk:latest. This approach is deprecated and will be removed in the future
```

Another option would be to register formally as OSS with docker which subject to annual approval I believe allows consumers to not consume pulls every time. Probably easier, to just push to ghcr.io though

**Comment by bsideup** [comment]
We applied for the rate limit exemption for http://hub.docker.com/r/testcontainers/ and it should be working now. Please let us know if you still see the rate limit errors for `testcontainers/*` images 👍

**Comment by adriancole** [comment]
applied and accepted I assume? zipkin is still not accepted, though applied. would be nice if they had an indicator like twitter's "verified accounts" for this

**Comment by bsideup** [comment]
yes, they got back to us and confirmed that we "passed". Since then, I've seen some weird 404 errors, but no rate limit-related ones :D
