### ISSUE TITLE
Support s390x architecture

### ISSUE THREAD

**Issue by codefromthecrypt** [testcontainers/moby-ryuk#18]
@BbolroC has requested zipkin to support s390x architecture, and we use testcontainers. #15 has notes about arm64 which are relevant here. I noticed that if you use very latest qemu.. it might work, but I can't tell if `go mod download` is slow or hung as it never completes when I run on s390x

**Comment by adriancole** [comment]
@BbolroC can you chase this up? I'm planning to not pay attention as there are other fish to fry

**Comment by adriancole** [comment]
fyi here's where I got on my mac setup with `multiarch/qemu-user-static:5.1.0-7`

```Dockerfile
FROM golang:1.15.4-alpine3.12 as workspace
WORKDIR /go/src/github.com/testcontainers/moby-ryuk
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 go build -i -v -ldflags '-s' -o ./bin/moby-ryuk ./


FROM ghcr.io/openzipkin/alpine:3.12.1
COPY --from=workspace /go/src/github.com/testcontainers/moby-ryuk/bin/moby-ryuk /app
CMD ["/app"]
```


```
$ docker buildx build --progress plain --tag ghcr.io/openzipkin/testcontainers-ryuk:latest --platform=linux/s390x --load .
--snip--
#10 [workspace 4/6] RUN go mod download
#10 1.615 go: github.com/Microsoft/go-winio@v0.4.6: Get "https://proxy.golang.org/github.com/%21microsoft/go-winio/@v/v0.4.6.mod": tls: invalid signature by the server certificate: ECDSA verification failure
#10 ERROR: executor failed running [/bin/sh -c go mod download]: runc did not terminate sucessfully
```

The error is mentioned here golang/go#40949 looks like people avoided packages. I also tried golang 14 same

**Comment by rnorth** [comment]
I've had a quick play today and so far, so good. I wonder if something has been fixed in QEMU in recently - it's hard to know.

I'll aim to tackle this and #15 in the next couple of days.

My draft PR is here if anybody is interested: https://github.com/testcontainers/moby-ryuk/pull/21

**Comment by rnorth** [comment]
This was done in #21
