### ISSUE TITLE
testcontainers/ryuk:0.3.0 disappeared from quay.io

### ISSUE THREAD

**Issue by jekkel** [testcontainers/moby-ryuk#20]
For unknown reasons the latest stable version `0.3.0` seem to have [disappeared from quay.io](https://quay.io/repository/testcontainers/ryuk?tab=history). I'm pretty sure it has been there because it's the default location baked into at least the java library and now our builds started to fail because it cannot be pulled anymore.

Note `v0.3.0` is available via docker hub, but is not being pulled from there by certain versions of test containers.

**Comment by rnorth** [comment]
Hi @jekkel 
That sounds strange, but we don't think that this image was ever actually published to quay.io...

I checked where we last referenced it, and it appears 0.2.3 was the last:

https://github.com/testcontainers/testcontainers-java/commit/fe2102a99ce323a1fa00913104954264bda44a86#diff-87c8b4b1adf608eaf354a256ad4a5af86049d324cc351c6f6f6b94e96232cbd7L75

Have you seen anything that we might have overlooked?

**Comment by jekkel** [comment]
Mmh. I'm pretty sure we used to pull it from there in our CI... but in the meantime we found a viable working workaround. So Feel free to close the issue then.

Thanks for responding though!
