### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by PSanetra** [testcontainers/moby-ryuk#34]
Hi, do you have an ETA for a new release that contains the latest changes?

**Comment by PSanetra** [comment]
@bsideup can you create a new release so that the official container image can be used in [testcontainers/testcontainers-dotnet](https://github.com/testcontainers/testcontainers-dotnet)?

**Comment by kiview** [comment]
Thanks for the ping @PSanetra, we will look into this 👍

**Comment by kiview** [comment]
We just released https://github.com/testcontainers/moby-ryuk/releases/tag/0.3.4.
