### ISSUE TITLE
WCOW Support

### ISSUE THREAD

**Issue by PSanetra** [testcontainers/moby-ryuk#35]
It would be nice to support Ryuk in a windows container environment. Would you be open for such a contribution or do you consider this out-of-scope as the [Java Testcontainers do not support WCOW](https://www.testcontainers.org/supported_docker_environment/windows/#windows-container-on-windows-wcow) at the moment?

It would be nice to have this for the [dotnet-testcontainers](https://github.com/HofmeisterAn/dotnet-testcontainers) project.

**Comment by kiview** [comment]
Hey @PSanetra, sorry for answering late.
 
I think this is a nice idea since a WCOW image of Ryuk would also help testcontainers-java in this regard (missing WCOW Ryuk is a blocker there as well). 

We would be very happy if you could help in adding this support. How do you estimate the effort?

**Comment by gesellix** [comment]
The PR #40 adds a Windows native layer to the existing multi-arch image.

**Comment by narcis-ro** [comment]
Hey guys. Are you still planning to merge either versions? Kind regards

**Comment by gesellix** [comment]
-> https://github.com/testcontainers/moby-ryuk/pull/40#issuecomment-1960321233

**Comment by gesellix** [comment]
A clean pull request is open for discussion at https://github.com/testcontainers/moby-ryuk/pull/110

**Comment by narcis-ro** [comment]
PR was merged. When is it gonna be released?

**Comment by gesellix** [comment]
#120 ist more or less finished. I think after that some dependabot PRs might be merged, too, and then everything should be ready for a release.

**Comment by gesellix** [comment]
Looks like a new release is available: https://github.com/testcontainers/moby-ryuk/releases/tag/0.7.0
:)

**Comment by mdelapenya** [comment]
Indeed, let's reopen this issue in the case a bug in the windows container is found.

Thank you all for your patience 🙏🙇
