### ISSUE TITLE
Join the Docker Verified Publisher Program

### ISSUE THREAD

**Issue by jaecktec** [testcontainers/moby-ryuk#36]
### Context
Docker requires companies to purchase docker accounts and make their employees use these accounts

### Problem
Some companies restrict access to community images

### Proposal
join the [Docker Verified Publisher Program](https://docs.docker.com/docker-hub/publish/) so restricted company accounts can use testcontainers

**Comment by kiview** [comment]
Hi @jaecktec, thanks for bringing this to our attention. 

In the context of your Testcontainers usage (assuming this is the background), are all other images you are using in your tests besides Ryuk already part of the Docker Verified Publisher Program?

**Comment by jaecktec** [comment]
`localstack/localstack` is also missing

**Comment by jaecktec** [comment]
I'm using testcontainers with localstack, so afaik this is the only one used for now. I will open the same issue on localstack as well 🙈
