### ISSUE TITLE
Merge changes from PSanetra/moby-ryuk fork

### ISSUE THREAD

**Issue by hiredgunhouse** [testcontainers/moby-ryuk#37]
As testcontainers/testcontainers-dotnet is using PSantera/moby-ryuk fork would you please consider merging those changes back so that they could switch back to testcontainers/moby-ryuk?

**Comment by PSanetra** [comment]
@hiredgunhouse The necessary changes are already merged, but there is no release with the latest changes on master :see_no_evil:

**Comment by HofmeisterAn** [comment]
@testcontainers/core-team any ETA? An official version for `tc-dotnet` would be nice.

**Comment by kiview** [comment]
Since the changes are merged, I am closing this issue. Expect the release soon.
