### ISSUE TITLE
Would it be possible to make the image pruning optional?

### ISSUE THREAD

**Issue by pe-st** [testcontainers/moby-ryuk#41]
For some time now Ryuk is also cleaning up images (https://github.com/testcontainers/moby-ryuk/pull/13, https://github.com/testcontainers/moby-ryuk/pull/25).
It does [so](https://github.com/testcontainers/moby-ryuk/blob/master/main.go#L194) with an [ImageSearch filter](https://docs.docker.com/engine/api/v1.41/#tag/Image/operation/ImageSearch) using labels (see Testcontainer's `RyukResourceReaper` class or Ryuk's README).

With older docker versions where ImageSearch's filter doesn't support labels (e.g. [Docker 1.13](https://docs.docker.com/engine/api/v1.26/#tag/Image/operation/ImageSearch)) this results in deleting ALL currently unused images, see this discussion with @kiview on [stackoverflow](https://stackoverflow.com/questions/71600706/why-docker-image-is-removed-at-the-end-of-the-tests-when-using-testcontainers#comment126884448_71643854).

In my CI/CD workflow (that runs on a build server with Docker 1.13, without the possibility to upgrade to a newer Docker version) I was forced to disable Ryuk altogether (the pipeline builds a docker image that is run by Testcontainers to perform tests, and only when the image passes all tests it is then promoted to the next pipeline steps), because after a successful test with Testcontainers the image was not referenced anymore and thus removed by Ryuk.

So here's my question (I'm not familiar with GO and don't know what is easily possible...):

Would it be possible to make the image pruning optional with Ryuk? Or should there be rather a warning and/or documentation in Testcontainers itself that Ryuk should be disabled for older Docker versions?

**Comment by kiview** [comment]
Hey @pe-st, thanks for starting this discussion.

IMO image pruning is one of the core features of Ryuk, so making it optional seems not very well aligned with the core feature set of Ryuk. Making it optional from a technical level (don't prune at all for unsupported Docker versions) would be possible, but I am really not convinced that we should explicitly support Docker versions as old as 1.13 (which is from the beginning of 2017).

On the other hand, Testcontainers users can always specify custom Ryuk images, so there exists the possibility to run a patched Ryuk version for those edge cases.

> Or should there be rather a warning and/or documentation in Testcontainers itself that Ryuk should be disabled for older Docker versions?

We strongly advise **against** disabling Ryuk as Testcontainers maintainers. This is often done out of cargo-cult reasons and consequences, especially on CI, are not always well understood. Therefore, I don't think we would explicitly document it in this way.

**Comment by kiview** [comment]
I'll close this issue for now, since I think of it as an edge case. However, since I understand that these CI environments with very old Docker versions are out there and upgrading them might be outside of the control of the individual developer, I believe using a custom patched version of Ryuk (I think just removing these lines is ok: https://github.com/testcontainers/moby-ryuk/blob/master/main.go#L222-L234) is a usable workaround.

**Comment by pe-st** [comment]
> Thank you, I will try that!

It took some time, but [here](https://github.com/pe-st/moby-ryuk/tree/feature/no-image-pruning) is my fork with a patched version of Ryuk. And I wrote a [blog article](https://pesche.schlau.ch/2023/01/09/ryuk-the-resource-reaper/) about it ;-)

@kiview @HofmeisterAn

**Comment by kiview** [comment]
Thanks so much for sharing your patched version and the blog article @pe-st, super helpful to the community 🙏
