### ISSUE TITLE
GKE / containerd - Pods unable to connect to Ryuk

### ISSUE THREAD

**Issue by mikamakusa** [testcontainers/moby-ryuk#42]
Hi,

I'm working on Gitlab Runners powered by GKE, i'm running tests with a Gradle project which include calls to a testcontainer Ryuk which always fails no matter how I try it.

Here's the log showing the error : 
```
Note: Recompile with -Xlint:deprecation for details.

> Task :processTestResources
> Task :testClasses
> Task :test

xxxxxxxxxxxTest > initializationError FAILED
    java.lang.IllegalStateException at RyukResourceReaper.java:132
09:48:00.342 [testcontainers-ryuk] WARN org.testcontainers.utility.RyukResourceReaper - Can not connect to Ryuk at localhost:49153
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.testcontainers.utility.RyukResourceReaper.lambda$null$0(RyukResourceReaper.java:92)
        at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
        at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$1(RyukResourceReaper.java:88)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Since GKE push to use containerd instead of no matter which Kubernetes version we use, I tried with the following lines in the Gitlab Runner manifest :  
```
- name: "TESTCONTAINERS_HOST_OVERRIDE"
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```

But the error message remains...

For now, I have no other choice to continue to use the Gitlab Runners running on an oldest cluster...but the idea is to get rid of this one and use the newest one.

Any help will be good, thanks in advance.

**Comment by kiview** [comment]
Hey @mikamakusa, 
since you have an ephemeral CI environment with Gitlab CI, it might be ok to disable Ryuk, depending on the Docker setup you use (i.e., if you can ensure container cleanup yourself).

I don't think this is an issue with Ryuk itself, you should consider raising a question at https://github.com/testcontainers/testcontainers-java. 

As mentioned above, if you ensure container cleanup, you can disable Ryuk:
https://www.testcontainers.org/features/configuration/#disabling-ryuk

It might also be the case, that your environment requires Ryuk to run in `prvileged` mode, to allow mounting of the Docker socket:
https://www.testcontainers.org/features/configuration/#customizing-ryuk-resource-reaper

I'll close this issue here.

**Comment by mikamakusa** [comment]
Hi,

Thank you for you quick answer.

But I think I need to give more information.

We have two GKE cluster, the old one with the version 1.21.14-gke.2700 and docker (built approximately one year ago), and the newest with the version 1.23.8-gke.1900 and containerd (since it's not possible, on GKE, to build a cluster with docker whatever the version chosen).

We run the same version of Gitlab Runners on both of them (since I've accidentaly deleted 2 runners namespaces last week), their configuration is the same. 
On the oldest cluster, we have no problem related to ryuk...only on the newest cluster. 

I thought updating the Gitlab Runners with 
```
env:
        - name: TESTCONTAINERS_HOST_OVERRIDE
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```
or
```
env:
        - name: TESTCONTAINERS_RYUK_DISABLED 
          value: "true"
```
or 
```
env:
        - name: TESTCONTAINERS_RYUK_DISABLED 
          value: "true"
        - name: TESTCONTAINERS_HOST_OVERRIDE
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```

But it has no effects, it still returns the same error and I can't update the application code directly (I'm not the developper)
