### ISSUE TITLE
Support docker image pruning as well

### ISSUE THREAD

**Issue by isen-ng** [testcontainers/moby-ryuk#6]
The current Ryuk can now prune containers, networks and volumes but it cannot prune docker images.

Since now testcontainer-java can now [create images and run then on the fly](https://www.testcontainers.org/features/creating_images/), Ryuk should be able to prune them.

They are now pruned using a shutdown hook in Java, but I think that could not be absolutely reliable. That's probably the reason why Ryuk was created in the first place.

So, I hope Ryuk can support pruning images as well.

**Comment by pe-st** [comment]
I guess this issue could be closed, see https://github.com/testcontainers/moby-ryuk/pull/13 and https://github.com/testcontainers/moby-ryuk/pull/25

**Comment by kiview** [comment]
You are right @pe-st, thanks for letting us know.
