### ISSUE TITLE
Ryuk Docker Extension

### ISSUE THREAD

**Issue by collabnix** [testcontainers/moby-ryuk#68]
Docker Extensions lets you use third-party tools within Docker Desktop to extend its functionality. Extensions allows developers to seamlessly connect their favorite development tools to your application development and deployment workflows.

It would be great to have Ryuk UI and use it as a Docker Extension. What do you think?

**Comment by kiview** [comment]
Hey @collabnix, could you please provide more context on the use cases for such an extension?
