### ISSUE TITLE
volumes are not deleted on docker 24.0.1

### ISSUE THREAD

**Issue by reda-alaoui** [testcontainers/moby-ryuk#79]
# Context

Seems related to https://github.com/docker/cli/issues/4028

# How to reproduce with the CLI

1. Create a volume
    ```bash
    $ docker volume create foo --label foo=bar
    ```
2. Try to prune it with a simple filter:
    ```bash
    $ docker volume prune --filter "label=foo=bar"
    WARNING! This will remove anonymous local volumes not used by at least one container.
    Are you sure you want to continue? [y/N] y
    Total reclaimed space: 0B
    $ docker volume ls --filter "label=foo=bar"
    DRIVER    VOLUME NAME
    local     foo
    ```

The volume is still there, not removed.

# Workaround with the CLI

```bash
$ docker volume prune --filter "label=foo=bar" --filter "all=1"
WARNING! This will remove anonymous local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Volumes:
foo

Total reclaimed space: 0B
$ docker volume ls --filter "label=foo=bar"
DRIVER    VOLUME NAME
```

# What has this to do with Ryuk ?

Ryuk has the same behaviour as the Docker CLI. It emits a command without `all=1` that has no effect on the volumes.

**Comment by HofmeisterAn** [comment]
This issue should be fixed with https://github.com/testcontainers/moby-ryuk/pull/77 (version 0.5.1).
