### ISSUE TITLE
Re-push new image to quay.io for schema version 2 of manifest

### ISSUE THREAD

**Issue by kageiit** [testcontainers/moby-ryuk#9]
We are trying to download images for ryuk from quay.io using https://github.com/NotGlop/docker-drag which does not support schema 1. The current ryuk images have been pushed with schema version 1 of the manifest. Quay.io supports manifest schema version 2 fully now - https://github.com/moby/buildkit/issues/409#issuecomment-588381613

Can we re-push to have schema 2 compatible images?

**Comment by bsideup** [comment]
We're migrating to Docker Hub, so this shouldn't be necessary anymore 👍
